name: PlatformIO CI
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [esp8266-arduino, esp32-arduino, esp32-idf]

    steps:
      - uses: actions/checkout@v6
      
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Run PlatformIO Build
        run: pio run -e ${{ matrix.env }}
